### ISSUE TITLE
Recupération du fichier PDF

### ISSUE THREAD

**Issue by titoff002** [ekyna/Colissimo#1]
Bonjour,

J'ai testé votre code colissimo : jolie travail.

J'ai une question pour la génération des étiquettes : 
```
echo <<<EOT
Data:
Parcel number: {$response->labelV2Response->parcelNumber}
Parcel number partner: {$response->labelV2Response->parcelNumberPartner}
Pdf Url: {$response->labelV2Response->pdfUrl}
EOT; 
```
La variable `$response->labelV2Response->pdfUrl` est toujours vide : comment faire pour récupérer le fichier PDF de l'étiquette ou l'url renseigné ?

Merci à vous.

**Comment by titoff002** [comment]
Bonjour,
Autre question :
J'utilise le productcode suivant `$request->letter->service->productCode = Postage\Enum\ProductCode::BPR;`

Avec ce productcode, j'ai le code d'erreur suivant :

```
Message [30403] (ERROR): Le code ou l'adresse point de retrait n'a pas été transmis
Data:
Parcel number: 
Parcel number partner: 
Pdf Url:
```

Comment doit on renseigner le code ou l'adresse du point relais ?

Merci à vous.

**Comment by titoff002** [comment]
Résolu.
Merci.

**Comment by ekyna** [comment]
Bonjour @titoff002 

Désolé j'étais en déplacement ces derniers jours. Ravi d'apprendre que vous avez trouvé la solution.
