### ISSUE TITLE
Création etiquette retour

### ISSUE THREAD

**Issue by titoff002** [ekyna/Colissimo#2]
Bonjour,

Pouvez-vous m'expliquer comment générer une étiquette retour à l'aide de vos classes ?

Merci pour votre travail.

Cordialement,

Christophe

**Comment by ekyna** [comment]
Bonjour,

Je n'ai plus mis le nez dans la documentation depuis un bon moment mais il me semble que vous pouvez utiliser la méthode GenerateLabel comme dans [cet example](https://github.com/ekyna/Colissimo/blob/master/examples/generate_label.php).

Il faut juste inverser les adresses (votre client est l'expéditeur et vous êtes le destinataire) et utilise le code produit CORE (constante Postage\Enum\ProductCode::CORE).
